spring:
  application:
    name: gateway
  cloud:
    zookeeper:
      connect-string: localhost:2181

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    books:
       serviceId: book

    accounts:
       serviceId: account

server:
  port: 9000
