spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    books:
       serviceId: book

    accounts:
       serviceId: account
       
    demo:
       serviceId: demo 

server:
  port: 9000
