
spring:
  cloud:
    euruka:
      connect-string: http://registry:8761

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    user-service:
       serviceId: user-service

    product-service:
       serviceId: product-service


server:
  port: 8080
